const express = require('express');
const router = express();
const bodyParser = require('body-parser');
router.set(bodyParser.urlencoded({extended: false}));
router.set(bodyParser.json());
router.use(express.static('public'));
const path = require('path');
const pug = require('pug');
router.set("view engine", "pug");
router.set('views', path.join(__dirname, '../views'));

let breaknews = require('./breaknews.js');
let contacts = require('./contacts.js');
let categories = require('./categories.js');
let subcategories = require('./subcategories.js');
let articles = require('./articles.js');
let highlight = require('./highlight.js');
let slideshow = require('./slideshow.js');
let videos = require('./videos.js');
let popular = require('./popular.js');
let about = require('./about.js');
let newsletter = require('./newsletter.js');
let setting = require('./setting.js');
let newsletterSub = require('./newsletter-sub.js');
let home = require('./home.js');
let login = require('./login.js');
let account = require('./account.js');
router.use(breaknews);
router.use(contacts);
router.use(categories);
router.use(subcategories);
router.use(articles);
router.use(highlight);
router.use(slideshow);
router.use(videos);
router.use(popular);
router.use(about);
router.use(newsletter);
router.use(setting);
router.use(newsletterSub);
router.use(home);
router.use(account);
router.use(login);
module.exports = router;